channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - numpy=1.22
  - scipy
  - matplotlib
  - scikit-learn
  - pandas
  - pytorch=1.13
  - joblib 
  - cxx-compiler # required by tick
  - dill # required by tick
  - swig # required by tick
  - pip
  - pip:
    - pynvml
  - tqdm
